# Generated by Django 2.1.5 on 2019-06-06 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_system', '0004_courserecord_scorerecord_studyrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeWorkRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='courserecord',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'depart__title': '教学部'}, on_delete=django.db.models.deletion.CASCADE, to='manage_system.UserInfo', verbose_name='讲师'),
        ),
        migrations.AddField(
            model_name='homeworkrecord',
            name='course_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_system.CourseRecord', verbose_name='第几天课程'),
        ),
        migrations.AddField(
            model_name='homeworkrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_system.Student', verbose_name='学员'),
        ),
    ]
