# Generated by Django 2.1.5 on 2019-06-06 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_system', '0005_auto_20190606_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworkrecord',
            name='course_record',
        ),
        migrations.RemoveField(
            model_name='homeworkrecord',
            name='student',
        ),
        migrations.DeleteModel(
            name='HomeWorkRecord',
        ),
    ]
