# Generated by Django 2.1.5 on 2019-06-07 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_system', '0006_auto_20190606_0132'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeWorkStudentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework', models.TextField(blank=True, null=True, verbose_name='作业')),
                ('score', models.IntegerField(default=0, help_text='最终得分', verbose_name='分值')),
                ('avatar', models.FileField(default='/avatars/liuyifei1.jpg', upload_to='avatars/')),
                ('course_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_system.CourseRecord', verbose_name='第几天课程')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_system.Student', verbose_name='学员')),
            ],
        ),
    ]
