# Generated by Django 2.1.5 on 2019-06-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_system', '0007_homeworkstudentrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkstudentrecord',
            name='avatar',
            field=models.FileField(default='/avatars/zhoukunyi.jpg', upload_to='avatars/'),
        ),
    ]
