# Generated by Django 2.1.5 on 2019-06-12 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_system', '0008_auto_20190612_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkstudentrecord',
            name='avatar',
            field=models.FileField(upload_to='avatars/', verbose_name='上传文件'),
        ),
    ]
